---
abstract: 'A system to rewrite text using regexp-based rules'
author:
  - 'Alberto Simoes <ambs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-RewriteRules
no_index:
  directory:
    - t
    - inc
requires:
  Filter::Simple: 0.78
  Test::More: 0
version: 0.25
