--- #YAML:1.0
name:                Text-RewriteRules
version:             0.11
abstract:            A system to rewrite text using regexp-based rules
license:             ~
author:              
    - Alberto Simões <ambs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.43_01
distribution_type:   module
requires:     
    Filter::Simple:                0.78
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
